
version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gosec
  exclusions:
    presets:
      - std-error-handling

formatters:
  enable:
    - gofmt
    - goimports
    - golines
