project_name: image-triggers

env:
  - GO11MODULE=on

before:
  hooks:
    - go mod download

builds:
  - main: main.go
    binary: image-triggers
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

snapshot:
  name_template: "git-{{.ShortCommit}}"

# dockers:
#   - image_templates:
#       - "panubo/image-triggers:{{.Major}}"
#       - "panubo/image-triggers:{{.Major}}.{{.Minor}}"
#       - "panubo/image-triggers:{{.Major}}.{{.Minor}}.{{.Patch}}"
#       - "panubo/image-triggers:latest"
#     skip_push: true

dockers:
  - image_templates:
      - "panubo/image-triggers:{{ .Version }}-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
    skip_push: true
  - image_templates:
      - "panubo/image-triggers:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    skip_push: true
docker_manifests:
  - name_template: "panubo/image-triggers:{{ .Version }}"
    image_templates:
      - "panubo/image-triggers:{{ .Version }}-amd64"
      - "panubo/image-triggers:{{ .Version }}-arm64v8"
    skip_push: true
  - name_template: "panubo/image-triggers:{{.Major}}.{{.Minor}}"
    image_templates:
      - "panubo/image-triggers:{{ .Version }}-amd64"
      - "panubo/image-triggers:{{ .Version }}-arm64v8"
    skip_push: true

release:
  github:
    owner: panubo
    name: image-triggers
  draft: true
  disable: true
