# Source: https://github.com/panubo/reference-github-actions/blob/main/pre-commit-configs/golang.pre-commit-config.yaml

repos:
  - repo: local
    hooks:
      - id: goreleaser-check
        name: Validate goreleaser config yaml
        description: Validate goreleaser config yaml
        # Goreleaser has an issue with pre-commit if it thinks it has access to the TTY so we use `cat` to trick it.
        entry: bash -c "set -o pipefail; goreleaser check | cat"
        language: system
        files: ".goreleaser.yml"
        pass_filenames: false
      - id: go-mod-tidy
        name: go mod tidy
        description: go mod tidy
        entry: bash -c "set -o pipefail; go mod tidy; git diff --exit-code go.* >/dev/null || { echo \"go.mod or go.sum modified, add to your commit.\"; exit 1; }"
        language: system
        pass_filenames: false
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.5.0
    hooks:
      - id: golangci-lint-full
        stages: [pre-commit]
      - id: golangci-lint-fmt
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
