# Source: https://github.com/panubo/reference-github-actions/blob/main/scan-image.yml

name: Scan

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'The release tag to scan (e.g., v1.2.3). Defaults to "latest".'
        required: true
        default: 'latest'
  schedule:
    # Weekly on Mondays at 00:00 UTC
    - cron: '0 0 * * 1'

env:
  REGISTRY: quay.io

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Get target tag
        id: get_tag
        uses: actions/github-script@v7
        with:
          script: |
            const release = '${{ github.event.inputs.release || 'latest' }}';
            let tagName;

            if (release === 'latest') {
              console.log('Fetching the latest release...');
              const latestRelease = await github.rest.repos.getLatestRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              tagName = latestRelease.data.tag_name;
              console.log(`Latest release tag found: ${tagName}`);
            } else {
              tagName = release;
              console.log(`Using provided release tag: ${tagName}`);
            }

            // Strip the 'v' prefix if it exists
            const imageTag = tagName.replace(/^v/, '');
            console.log(`Image tag to be used for scanning: ${imageTag}`);
            core.setOutput('tag', imageTag);

      - name: Run Trivy vulnerability scanner
        id: trivy_scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'image'
          image-ref: '${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.get_tag.outputs.tag }}'
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'HIGH,CRITICAL'
          exit-code: 1
          ignore-unfixed: true

      - name: Publish Trivy scan results to summary
        if: success() || failure()
        run: |
          echo "### Trivy Scan Report for ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.get_tag.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
          if [[ ${{ steps.trivy_scan.outcome }} == 'failure' ]]; then
            echo "**Scan failed! Found vulnerabilities with HIGH or CRITICAL severity.**" >> $GITHUB_STEP_SUMMARY
          else
            echo "**Scan completed successfully. No HIGH or CRITICAL severity vulnerabilities found.**" >> $GITHUB_STEP_SUMMARY
          fi

          if [[ -s trivy-results.txt ]]; then
            {
              echo "<details><summary>Click to see full scan report</summary>"
              echo ""
              echo '```'
              cat trivy-results.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          else
            echo "No Trivy output file was generated. The image might not exist or the scan failed to start." >> $GITHUB_STEP_SUMMARY
          fi
